In [1]:
import pandas as pd
from matplotlib import pyplot as plt
from matplotlib import dates as mpl_dates
import numpy as np
import seaborn as sns

In [2]:
data82018 = pd.read_csv ('2018-08.csv')
data112018 = pd.read_csv ('2018-11.csv')
data52019 = pd.read_csv ('2019-05.csv')
data102019 = pd.read_csv ('2019-10.csv')

In [2]:
df1 = pd.read_csv ('2018-08.csv')

In [3]:
df2 = pd.read_csv ('ENutrients_2018-08.csv',  encoding="ISO-8859-1")

In [11]:
df1

,latitude,longitude,date,depth,temperature,salinity,chl_ctd,pc_ctd,cdom_ctd,chl_a676,Unnamed: 10
0,41.3639,-71.4220,2018-08-22 20:05:33.0,4,22.9616,31.3731,3.0008,0.1708,2.2575,6.0672,NaN
1,41.3397,-71.4215,2018-08-22 20:15:34.0,4,22.9605,31.3645,1.4036,0.0000,3.7926,4.5728,NaN
2,41.3143,-71.4218,2018-08-22 20:25:34.0,4,22.8414,31.5827,1.0527,0.0854,9.7975,3.6196,NaN
3,41.2886,-71.4227,2018-08-22 20:35:34.0,4,22.6832,31.8200,0.6050,0.0640,2.5284,2.4087,NaN
4,41.2631,-71.4226,2018-08-22 20:45:34.0,4,22.2266,32.0359,0.6655,0.1067,12.1454,2.2538,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1153,36.6353,-75.0009,2018-08-30 23:09:42.0,4,27.3766,31.0626,0.1210,0.0854,1.1739,1.7724,NaN
1154,36.6121,-75.0006,2018-08-30 23:19:42.0,4,27.3393,31.0169,0.1089,0.0427,1.4448,1.7669,NaN
1155,36.5841,-75.0000,2018-08-30 23:29:42.0,4,27.5079,30.4349,0.1452,0.0427,1.5351,1.8033,NaN
1156,36.5565,-75.0001,2018-08-30 23:39:42.0,4,27.5168,30.4410,0.1452,0.0640,1.4448,1.7968,NaN
1157,36.5290,-75.0004,2018-08-30 23:49:42.0,4,27.6020,30.3250,0.1331,0.0427,1.4448,1.8052,NaN

df2

In [12]:
df2

,latitude,longitude,date,depth,Bottom Depth(m),Sample Press(dBar),Temperature(C),Salinity(psu),Sigma-t,Sigma-Theta,Oxygen(mg/L),Chlorophyll Fluorescence(Âµg/L),NO3+NO2(ÂµM),Si(OH)4 (ÂµM),PO4 (ÂµM)
0,41.3639,-71.4220,05:33.0,4.0,61.0,2.0,20.5540,32.3729,22.6140,22.6141,7.48715,0.609925,0.09,1.01,0.31
1,41.1282,-71.0219,55:34.0,4.0,67.0,2.0,13.0719,32.1046,24.1367,24.1368,8.67045,3.278280,0.59,2.32,0.38
2,40.9404,-70.7567,15:34.0,4.0,44.0,3.0,18.3394,32.2607,23.0926,23.0928,8.03996,1.686100,0.09,1.66,0.23
3,40.8762,-70.3816,25:34.0,4.0,53.0,3.0,16.8980,32.3425,23.4993,23.4995,8.24726,1.324870,0.04,1.16,0.39
4,40.4664,-69.9003,48:27.0,4.0,39.0,3.0,18.2030,32.3250,23.1751,23.1752,7.95340,3.973100,0.09,0.29,0.36
5,40.8105,-69.1302,28:27.0,4.0,64.0,3.0,17.2037,32.2708,23.3730,23.3731,8.14901,1.482800,0.09,1.53,0.25
6,40.6436,-68.3372,38:26.0,4.0,61.0,10.0,19.5463,32.4196,22.9117,22.9121,7.85928,1.424060,0.09,1.12,0.32
7,41.4818,-68.3369,28:27.0,4.0,67.0,10.0,13.0493,32.1139,24.1483,24.1485,8.64942,2.900740,0.70,2.35,0.54
8,41.4534,-67.8178,07:32.0,4.0,39.0,10.0,18.2044,32.3251,23.1748,23.1753,7.93584,3.883680,0.05,0.29,0.39
9,40.7645,-67.5984,27:31.0,4.0,64.0,10.0,NaN,NaN,NaN,NaN,NaN,2.719740,0.10,1.83,0.37
10,40.0251,-69.2298,10:50.0,4.0,53.0,12.0,16.2950,32.3521,23.6452,23.6456,8.30100,2.846980,0.05,1.66,0.50
11,40.1794,-70.3633,10:51.0,4.0,44.0,14.0,15.8942,32.2599,23.6646,23.6650,8.62438,3.634420,0.09,1.99,0.24
12,40.1194,-71.1449,20:51.0,4.0,61.0,19.0,12.8222,32.6560,24.6123,24.6128,9.48941,2.958710,0.41,1.35,0.43
13,40.2324,-71.8850,10:51.0,4.0,67.0,20.0,12.7276,32.1592,24.2459,24.2464,8.43779,2.376790,1.28,2.48,0.42
14,40.5764,-72.9134,10:23.0,4.0,39.0,21.0,18.2056,32.3251,23.1746,23.1754,7.91882,4.093690,0.04,0.43,0.43
15,40.0532,-73.7517,20:23.0,4.0,64.0,21.0,14.1696,32.4267,24.1642,24.1648,7.97431,1.670840,1.62,2.57,0.45
16,39.4307,-72.8647,50:24.0,4.0,248.0,22.0,19.7889,34.8207,24.6804,24.6814,7.85690,0.975593,0.10,1.06,0.17
17,39.2962,-72.5357,56:31.0,4.0,44.0,25.0,14.2500,32.2904,24.0423,24.0430,8.27137,3.721510,0.19,2.48,0.37
18,39.3337,-73.3573,46:30.0,4.0,248.0,31.0,15.8506,34.8324,25.6527,25.6538,7.76798,2.297100,2.29,2.50,0.50
19,39.5502,-73.9067,36:31.0,4.0,67.0,32.0,12.6375,32.2130,24.3049,24.3057,8.32659,1.806580,1.31,2.64,0.49
20,39.1722,-74.4051,36:30.0,4.0,53.0,35.0,15.2509,32.3775,23.8967,23.8978,7.77990,1.785270,0.71,2.59,0.46
21,38.7792,-74.0736,09:50.0,4.0,39.0,36.0,18.2094,32.3248,23.1734,23.1749,7.92575,3.978310,0.09,0.19,0.38
22,38.4777,-73.4073,19:49.0,4.0,67.0,40.0,12.6939,32.2904,24.3540,24.3550,8.24747,1.445230,1.66,2.60,0.52
23,38.4976,-74.4132,54:00.0,4.0,64.0,40.0,13.5422,32.4733,24.3283,24.3294,7.79910,1.014950,2.71,3.14,0.53
24,38.0192,-74.8676,29:50.0,4.0,44.0,41.0,13.1578,32.4603,24.3950,24.3961,7.88025,1.594900,0.86,6.53,0.67
25,37.7251,-74.3009,19:41.0,4.0,53.0,50.0,15.1565,32.3805,23.9195,23.9211,7.77602,1.820390,1.04,2.70,0.40
26,37.6279,-75.0514,39:41.0,4.0,64.0,50.0,13.2847,32.5039,24.4035,24.4049,7.77955,0.955544,2.83,3.40,0.59
27,37.3665,-75.2359,49:42.0,4.0,67.0,51.0,11.5826,32.3627,24.6182,24.6194,8.25351,1.211180,2.07,3.19,0.55
28,37.0883,-75.6720,26:03.0,4.0,248.0,52.0,12.2168,34.5628,26.2079,26.2093,6.97844,0.661353,7.38,4.47,0.66
29,36.9109,-74.9524,19:42.0,4.0,61.0,53.0,10.2736,32.8280,25.2103,25.2113,7.42241,0.652899,5.48,8.17,0.66
30,36.5290,-75.0004,49:42.0,4.0,64.0,61.0,12.7248,32.6154,24.5998,24.6014,7.70288,0.791004,2.97,3.48,0.54
31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [48]:
df3 = pd.concat ([df1, df2])

In [13]:
pd.to_datetime(df2["date"])

ParserError: hour must be in 0..23: 55:34.0

In [49]:
df3

,,latitude,longitude,date,depth,temperature,salinity,chl_ctd,pc_ctd,cdom_ctd,chl_a676,...,Sample Press(dBar),Temperature(C),Salinity(psu),Sigma-t,Sigma-Theta,Oxygen(mg/L),Chlorophyll Fluorescence(Âµg/L),NO3+NO2(ÂµM),Si(OH)4 (ÂµM),PO4 (ÂµM)
longitude,latitude,,,,,,,,,,,,,,,,,,,,,
-71.4220,41.3639,NaN,NaN,NaN,NaN,22.9616,31.3731,3.0008,0.1708,2.2575,6.0672,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
-71.4215,41.3397,NaN,NaN,NaN,NaN,22.9605,31.3645,1.4036,0.0000,3.7926,4.5728,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
-71.4218,41.3143,NaN,NaN,NaN,NaN,22.8414,31.5827,1.0527,0.0854,9.7975,3.6196,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
-71.4227,41.2886,NaN,NaN,NaN,NaN,22.6832,31.8200,0.6050,0.0640,2.5284,2.4087,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
-71.4226,41.2631,NaN,NaN,NaN,NaN,22.2266,32.0359,0.6655,0.1067,12.1454,2.2538,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
-75.0514,37.6279,37.6279,-75.0514,39:41.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,...,50.0,13.2847,32.5039,24.4035,24.4049,7.77955,0.955544,2.83,3.40,0.59
-75.2359,37.3665,37.3665,-75.2359,49:42.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,...,51.0,11.5826,32.3627,24.6182,24.6194,8.25351,1.211180,2.07,3.19,0.55
-75.6720,37.0883,37.0883,-75.6720,26:03.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,...,52.0,12.2168,34.5628,26.2079,26.2093,6.97844,0.661353,7.38,4.47,0.66
-74.9524,36.9109,36.9109,-74.9524,19:42.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,...,53.0,10.2736,32.8280,25.2103,25.2113,7.42241,0.652899,5.48,8.17,0.66
-75.0004,36.5290,36.5290,-75.0004,49:42.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,...,61.0,12.7248,32.6154,24.5998,24.6014,7.70288,0.791004,2.97,3.48,0.54

In [16]:
df1.index = pd.MultiIndex.from_frame(df1[["longitude","latitude"]])

In [17]:
df1

,,latitude,longitude,date,depth,temperature,salinity,chl_ctd,pc_ctd,cdom_ctd,chl_a676,Unnamed: 10
longitude,latitude,,,,,,,,,,,
-71.4220,41.3639,41.3639,-71.4220,2018-08-22 20:05:33.0,4,22.9616,31.3731,3.0008,0.1708,2.2575,6.0672,NaN
-71.4215,41.3397,41.3397,-71.4215,2018-08-22 20:15:34.0,4,22.9605,31.3645,1.4036,0.0000,3.7926,4.5728,NaN
-71.4218,41.3143,41.3143,-71.4218,2018-08-22 20:25:34.0,4,22.8414,31.5827,1.0527,0.0854,9.7975,3.6196,NaN
-71.4227,41.2886,41.2886,-71.4227,2018-08-22 20:35:34.0,4,22.6832,31.8200,0.6050,0.0640,2.5284,2.4087,NaN
-71.4226,41.2631,41.2631,-71.4226,2018-08-22 20:45:34.0,4,22.2266,32.0359,0.6655,0.1067,12.1454,2.2538,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
-75.0009,36.6353,36.6353,-75.0009,2018-08-30 23:09:42.0,4,27.3766,31.0626,0.1210,0.0854,1.1739,1.7724,NaN
-75.0006,36.6121,36.6121,-75.0006,2018-08-30 23:19:42.0,4,27.3393,31.0169,0.1089,0.0427,1.4448,1.7669,NaN
-75.0000,36.5841,36.5841,-75.0000,2018-08-30 23:29:42.0,4,27.5079,30.4349,0.1452,0.0427,1.5351,1.8033,NaN
-75.0001,36.5565,36.5565,-75.0001,2018-08-30 23:39:42.0,4,27.5168,30.4410,0.1452,0.0640,1.4448,1.7968,NaN
-75.0004,36.5290,36.5290,-75.0004,2018-08-30 23:49:42.0,4,27.6020,30.3250,0.1331,0.0427,1.4448,1.8052,NaN

In [19]:
df2.index = pd.MultiIndex.from_frame(df2[["longitude","latitude"]])

df2

In [20]:
df2

                    latitude  longitude     date  depth  Bottom Depth(m)  \
longitude latitude
-71.4220  41.3639    41.3639   -71.4220  05:33.0    4.0             61.0
-71.0219  41.1282    41.1282   -71.0219  55:34.0    4.0             67.0
-70.7567  40.9404    40.9404   -70.7567  15:34.0    4.0             44.0
-70.3816  40.8762    40.8762   -70.3816  25:34.0    4.0             53.0
-69.9003  40.4664    40.4664   -69.9003  48:27.0    4.0             39.0
-69.1302  40.8105    40.8105   -69.1302  28:27.0    4.0             64.0
-68.3372  40.6436    40.6436   -68.3372  38:26.0    4.0             61.0
-68.3369  41.4818    41.4818   -68.3369  28:27.0    4.0             67.0
-67.8178  41.4534    41.4534   -67.8178  07:32.0    4.0             39.0
-67.5984  40.7645    40.7645   -67.5984  27:31.0    4.0             64.0
-69.2298  40.0251    40.0251   -69.2298  10:50.0    4.0             53.0
-70.3633  40.1794    40.1794   -70.3633  10:51.0    4.0             44.0
-71.1449  40.1194    40.1194   -71.1449  20:51.0    4.0             61.0
-71.8850  40.2324    40.2324   -71.8850  10:51.0    4.0             67.0
-72.9134  40.5764    40.5764   -72.9134  10:23.0    4.0             39.0
-73.7517  40.0532    40.0532   -73.7517  20:23.0    4.0             64.0
-72.8647  39.4307    39.4307   -72.8647  50:24.0    4.0            248.0
-72.5357  39.2962    39.2962   -72.5357  56:31.0    4.0             44.0
-73.3573  39.3337    39.3337   -73.3573  46:30.0    4.0            248.0
-73.9067  39.5502    39.5502   -73.9067  36:31.0    4.0             67.0
-74.4051  39.1722    39.1722   -74.4051  36:30.0    4.0             53.0
-74.0736  38.7792    38.7792   -74.0736  09:50.0    4.0             39.0
-73.4073  38.4777    38.4777   -73.4073  19:49.0    4.0             67.0
-74.4132  38.4976    38.4976   -74.4132  54:00.0    4.0             64.0
-74.8676  38.0192    38.0192   -74.8676  29:50.0    4.0             44.0
-74.3009  37.7251    37.7251   -74.3009  19:41.0    4.0             53.0
-75.0514  37.6279    37.6279   -75.0514  39:41.0    4.0             64.0
-75.2359  37.3665    37.3665   -75.2359  49:42.0    4.0             67.0
-75.6720  37.0883    37.0883   -75.6720  26:03.0    4.0            248.0
-74.9524  36.9109    36.9109   -74.9524  19:42.0    4.0             61.0
-75.0004  36.5290    36.5290   -75.0004  49:42.0    4.0             64.0
NaN       NaN            NaN        NaN      NaN    NaN              NaN
          NaN            NaN        NaN      NaN    NaN              NaN
          NaN            NaN        NaN      NaN    NaN              NaN
          NaN            NaN        NaN      NaN    NaN              NaN
          NaN            NaN        NaN      NaN    NaN              NaN
          NaN            NaN        NaN      NaN    NaN              NaN
          NaN            NaN        NaN      NaN    NaN              NaN

                    Sample Press(dBar)  Temperature(C)  Salinity(psu)  \
longitude latitude
-71.4220  41.3639                  2.0         20.5540        32.3729
-71.0219  41.1282                  2.0         13.0719        32.1046
-70.7567  40.9404                  3.0         18.3394        32.2607
-70.3816  40.8762                  3.0         16.8980        32.3425
-69.9003  40.4664                  3.0         18.2030        32.3250
-69.1302  40.8105                  3.0         17.2037        32.2708
-68.3372  40.6436                 10.0         19.5463        32.4196
-68.3369  41.4818                 10.0         13.0493        32.1139
-67.8178  41.4534                 10.0         18.2044        32.3251
-67.5984  40.7645                 10.0             NaN            NaN
-69.2298  40.0251                 12.0         16.2950        32.3521
-70.3633  40.1794                 14.0         15.8942        32.2599
-71.1449  40.1194                 19.0         12.8222        32.6560
-71.8850  40.2324                 20.0         12.7276        32.1592
-72.9134  40.5764                 21.0         18.2056        32.3251
-73.7517  40.0532                 21.0         14.1696        32.4267
-72.8647  39.4307                 22.0         19.7889        34.8207
-72.5357  39.2962                 25.0         14.2500        32.2904
-73.3573  39.3337                 31.0         15.8506        34.8324
-73.9067  39.5502                 32.0         12.6375        32.2130
-74.4051  39.1722                 35.0         15.2509        32.3775
-74.0736  38.7792                 36.0         18.2094        32.3248
-73.4073  38.4777                 40.0         12.6939        32.2904
-74.4132  38.4976                 40.0         13.5422        32.4733
-74.8676  38.0192                 41.0         13.1578        32.4603
-74.3009  37.7251                 50.0         15.1565        32.3805
-75.0514  37.6279                 50.0         13.2847        32.5039
-75.2359  37.3665                 51.0         11.5826        32.3627
-75.6720  37.0883                 52.0         12.2168        34.5628
-74.9524  36.9109                 53.0         10.2736        32.8280
-75.0004  36.5290                 61.0         12.7248        32.6154
NaN       NaN                      NaN             NaN            NaN
          NaN                      NaN             NaN            NaN
          NaN                      NaN             NaN            NaN
          NaN                      NaN             NaN            NaN
          NaN                      NaN             NaN            NaN
          NaN                      NaN             NaN            NaN
          NaN                      NaN             NaN            NaN

                    Sigma-t  Sigma-Theta  Oxygen(mg/L)  \
longitude latitude
-71.4220  41.3639   22.6140      22.6141       7.48715
-71.0219  41.1282   24.1367      24.1368       8.67045
-70.7567  40.9404   23.0926      23.0928       8.03996
-70.3816  40.8762   23.4993      23.4995       8.24726
-69.9003  40.4664   23.1751      23.1752       7.95340
-69.1302  40.8105   23.3730      23.3731       8.14901
-68.3372  40.6436   22.9117      22.9121       7.85928
-68.3369  41.4818   24.1483      24.1485       8.64942
-67.8178  41.4534   23.1748      23.1753       7.93584
-67.5984  40.7645       NaN          NaN           NaN
-69.2298  40.0251   23.6452      23.6456       8.30100
-70.3633  40.1794   23.6646      23.6650       8.62438
-71.1449  40.1194   24.6123      24.6128       9.48941
-71.8850  40.2324   24.2459      24.2464       8.43779
-72.9134  40.5764   23.1746      23.1754       7.91882
-73.7517  40.0532   24.1642      24.1648       7.97431
-72.8647  39.4307   24.6804      24.6814       7.85690
-72.5357  39.2962   24.0423      24.0430       8.27137
-73.3573  39.3337   25.6527      25.6538       7.76798
-73.9067  39.5502   24.3049      24.3057       8.32659
-74.4051  39.1722   23.8967      23.8978       7.77990
-74.0736  38.7792   23.1734      23.1749       7.92575
-73.4073  38.4777   24.3540      24.3550       8.24747
-74.4132  38.4976   24.3283      24.3294       7.79910
-74.8676  38.0192   24.3950      24.3961       7.88025
-74.3009  37.7251   23.9195      23.9211       7.77602
-75.0514  37.6279   24.4035      24.4049       7.77955
-75.2359  37.3665   24.6182      24.6194       8.25351
-75.6720  37.0883   26.2079      26.2093       6.97844
-74.9524  36.9109   25.2103      25.2113       7.42241
-75.0004  36.5290   24.5998      24.6014       7.70288
NaN       NaN           NaN          NaN           NaN
          NaN           NaN          NaN           NaN
          NaN           NaN          NaN           NaN
          NaN           NaN          NaN           NaN
          NaN           NaN          NaN           NaN
          NaN           NaN          NaN           NaN
          NaN           NaN          NaN           NaN

                    Chlorophyll Fluorescence(Âµg/L)  NO3+NO2(ÂµM)  Si(OH)4 (ÂµM)  \
longitude latitude
-71.4220  41.3639                         0.609925         0.09          1.01
-71.0219  41.1282                         3.278280         0.59          2.32
-70.7567  40.9404                         1.686100         0.09          1.66
-70.3816  40.8762                         1.324870         0.04          1.16
-69.9003  40.4664                         3.973100         0.09          0.29
-69.1302  40.8105                         1.482800         0.09          1.53
-68.3372  40.6436                         1.424060         0.09          1.12
-68.3369  41.4818                         2.900740         0.70          2.35
-67.8178  41.4534                         3.883680         0.05          0.29
-67.5984  40.7645                         2.719740         0.10          1.83
-69.2298  40.0251                         2.846980         0.05          1.66
-70.3633  40.1794                         3.634420         0.09          1.99
-71.1449  40.1194                         2.958710         0.41          1.35
-71.8850  40.2324                         2.376790         1.28          2.48
-72.9134  40.5764                         4.093690         0.04          0.43
-73.7517  40.0532                         1.670840         1.62          2.57
-72.8647  39.4307                         0.975593         0.10          1.06
-72.5357  39.2962                         3.721510         0.19          2.48
-73.3573  39.3337                         2.297100         2.29          2.50
-73.9067  39.5502                         1.806580         1.31          2.64
-74.4051  39.1722                         1.785270         0.71          2.59
-74.0736  38.7792                         3.978310         0.09          0.19
-73.4073  38.4777                         1.445230         1.66          2.60
-74.4132  38.4976                         1.014950         2.71          3.14
-74.8676  38.0192                         1.594900         0.86          6.53
-74.3009  37.7251                         1.820390         1.04          2.70
-75.0514  37.6279                         0.955544         2.83          3.40
-75.2359  37.3665                         1.211180         2.07          3.19
-75.6720  37.0883                         0.661353         7.38          4.47
-74.9524  36.9109                         0.652899         5.48          8.17
-75.0004  36.5290                         0.791004         2.97          3.48
NaN       NaN                                  NaN          NaN           NaN
          NaN                                  NaN          NaN           NaN
          NaN                                  NaN          NaN           NaN
          NaN                                  NaN          NaN           NaN
          NaN                                  NaN          NaN           NaN
          NaN                                  NaN          NaN           NaN
          NaN                                  NaN          NaN           NaN

                    PO4 (ÂµM)
longitude latitude
-71.4220  41.3639       0.31
-71.0219  41.1282       0.38
-70.7567  40.9404       0.23
-70.3816  40.8762       0.39
-69.9003  40.4664       0.36
-69.1302  40.8105       0.25
-68.3372  40.6436       0.32
-68.3369  41.4818       0.54
-67.8178  41.4534       0.39
-67.5984  40.7645       0.37
-69.2298  40.0251       0.50
-70.3633  40.1794       0.24
-71.1449  40.1194       0.43
-71.8850  40.2324       0.42
-72.9134  40.5764       0.43
-73.7517  40.0532       0.45
-72.8647  39.4307       0.17
-72.5357  39.2962       0.37
-73.3573  39.3337       0.50
-73.9067  39.5502       0.49
-74.4051  39.1722       0.46
-74.0736  38.7792       0.38
-73.4073  38.4777       0.52
-74.4132  38.4976       0.53
-74.8676  38.0192       0.67
-74.3009  37.7251       0.40
-75.0514  37.6279       0.59
-75.2359  37.3665       0.55
-75.6720  37.0883       0.66
-74.9524  36.9109       0.66
-75.0004  36.5290       0.54
NaN       NaN            NaN
          NaN            NaN
          NaN            NaN
          NaN            NaN
          NaN            NaN
          NaN            NaN
          NaN            NaN

In [23]:
df1[df2.index]

KeyError: "None of [MultiIndex([( -71.422, 41.3639),\n            (-71.0219, 41.1282),\n            (-70.7567, 40.9404),\n            (-70.3816, 40.8762),\n            (-69.9003, 40.4664),\n            (-69.1302, 40.8105),\n            (-68.3372, 40.6436),\n            (-68.3369, 41.4818),\n            (-67.8178, 41.4534),\n            (-67.5984, 40.7645),\n            (-69.2298, 40.0251),\n            (-70.3633, 40.1794),\n            (-71.1449, 40.1194),\n            ( -71.885, 40.2324),\n            (-72.9134, 40.5764),\n            (-73.7517, 40.0532),\n            (-72.8647, 39.4307),\n            (-72.5357, 39.2962),\n            (-73.3573, 39.3337),\n            (-73.9067, 39.5502),\n            (-74.4051, 39.1722),\n            (-74.0736, 38.7792),\n            (-73.4073, 38.4777),\n            (-74.4132, 38.4976),\n            (-74.8676, 38.0192),\n            (-74.3009, 37.7251),\n            (-75.0514, 37.6279),\n            (-75.2359, 37.3665),\n            ( -75.672, 37.0883),\n            (-74.9524, 36.9109),\n            (-75.0004,  36.529),\n            (     nan,     nan),\n            (     nan,     nan),\n            (     nan,     nan),\n            (     nan,     nan),\n            (     nan,     nan),\n            (     nan,     nan),\n            (     nan,     nan)],\n           names=['longitude', 'latitude'])] are in the [columns]"

In [27]:
for index in df2.index:
    df1[index]

KeyError: (-71.422, 41.3639)

f

In [28]:
df1

,,latitude,longitude,date,depth,temperature,salinity,chl_ctd,pc_ctd,cdom_ctd,chl_a676,Unnamed: 10
longitude,latitude,,,,,,,,,,,
-71.4220,41.3639,41.3639,-71.4220,2018-08-22 20:05:33.0,4,22.9616,31.3731,3.0008,0.1708,2.2575,6.0672,NaN
-71.4215,41.3397,41.3397,-71.4215,2018-08-22 20:15:34.0,4,22.9605,31.3645,1.4036,0.0000,3.7926,4.5728,NaN
-71.4218,41.3143,41.3143,-71.4218,2018-08-22 20:25:34.0,4,22.8414,31.5827,1.0527,0.0854,9.7975,3.6196,NaN
-71.4227,41.2886,41.2886,-71.4227,2018-08-22 20:35:34.0,4,22.6832,31.8200,0.6050,0.0640,2.5284,2.4087,NaN
-71.4226,41.2631,41.2631,-71.4226,2018-08-22 20:45:34.0,4,22.2266,32.0359,0.6655,0.1067,12.1454,2.2538,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
-75.0009,36.6353,36.6353,-75.0009,2018-08-30 23:09:42.0,4,27.3766,31.0626,0.1210,0.0854,1.1739,1.7724,NaN
-75.0006,36.6121,36.6121,-75.0006,2018-08-30 23:19:42.0,4,27.3393,31.0169,0.1089,0.0427,1.4448,1.7669,NaN
-75.0000,36.5841,36.5841,-75.0000,2018-08-30 23:29:42.0,4,27.5079,30.4349,0.1452,0.0427,1.5351,1.8033,NaN
-75.0001,36.5565,36.5565,-75.0001,2018-08-30 23:39:42.0,4,27.5168,30.4410,0.1452,0.0640,1.4448,1.7968,NaN
-75.0004,36.5290,36.5290,-75.0004,2018-08-30 23:49:42.0,4,27.6020,30.3250,0.1331,0.0427,1.4448,1.8052,NaN

In [30]:
df1.ix[df1[index]]

AttributeError: 'DataFrame' object has no attribute 'ix'

In [36]:
for index in df2.index:
    df1.index[df1.loc[index]]

C:\Users\Barry\anaconda3\lib\site-packages\ipykernel_launcher.py:2: PerformanceWarning: indexing past lexsort depth may impact performance.

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [33]:
df2 = df2.dropna ()
print (df2)

                    latitude  longitude     date  depth  Bottom Depth(m)  \
longitude latitude
-71.4220  41.3639    41.3639   -71.4220  05:33.0    4.0             61.0
-71.0219  41.1282    41.1282   -71.0219  55:34.0    4.0             67.0
-70.7567  40.9404    40.9404   -70.7567  15:34.0    4.0             44.0
-70.3816  40.8762    40.8762   -70.3816  25:34.0    4.0             53.0
-69.9003  40.4664    40.4664   -69.9003  48:27.0    4.0             39.0
-69.1302  40.8105    40.8105   -69.1302  28:27.0    4.0             64.0
-68.3372  40.6436    40.6436   -68.3372  38:26.0    4.0             61.0
-68.3369  41.4818    41.4818   -68.3369  28:27.0    4.0             67.0
-67.8178  41.4534    41.4534   -67.8178  07:32.0    4.0             39.0
-69.2298  40.0251    40.0251   -69.2298  10:50.0    4.0             53.0
-70.3633  40.1794    40.1794   -70.3633  10:51.0    4.0             44.0
-71.1449  40.1194    40.1194   -71.1449  20:51.0    4.0             61.0
-71.8850  40.2324    40.2324   -71.8850  10:51.0    4.0             67.0
-72.9134  40.5764    40.5764   -72.9134  10:23.0    4.0             39.0
-73.7517  40.0532    40.0532   -73.7517  20:23.0    4.0             64.0
-72.8647  39.4307    39.4307   -72.8647  50:24.0    4.0            248.0
-72.5357  39.2962    39.2962   -72.5357  56:31.0    4.0             44.0
-73.3573  39.3337    39.3337   -73.3573  46:30.0    4.0            248.0
-73.9067  39.5502    39.5502   -73.9067  36:31.0    4.0             67.0
-74.4051  39.1722    39.1722   -74.4051  36:30.0    4.0             53.0
-74.0736  38.7792    38.7792   -74.0736  09:50.0    4.0             39.0
-73.4073  38.4777    38.4777   -73.4073  19:49.0    4.0             67.0
-74.4132  38.4976    38.4976   -74.4132  54:00.0    4.0             64.0
-74.8676  38.0192    38.0192   -74.8676  29:50.0    4.0             44.0
-74.3009  37.7251    37.7251   -74.3009  19:41.0    4.0             53.0
-75.0514  37.6279    37.6279   -75.0514  39:41.0    4.0             64.0
-75.2359  37.3665    37.3665   -75.2359  49:42.0    4.0             67.0
-75.6720  37.0883    37.0883   -75.6720  26:03.0    4.0            248.0
-74.9524  36.9109    36.9109   -74.9524  19:42.0    4.0             61.0
-75.0004  36.5290    36.5290   -75.0004  49:42.0    4.0             64.0

                    Sample Press(dBar)  Temperature(C)  Salinity(psu)  \
longitude latitude
-71.4220  41.3639                  2.0         20.5540        32.3729
-71.0219  41.1282                  2.0         13.0719        32.1046
-70.7567  40.9404                  3.0         18.3394        32.2607
-70.3816  40.8762                  3.0         16.8980        32.3425
-69.9003  40.4664                  3.0         18.2030        32.3250
-69.1302  40.8105                  3.0         17.2037        32.2708
-68.3372  40.6436                 10.0         19.5463        32.4196
-68.3369  41.4818                 10.0         13.0493        32.1139
-67.8178  41.4534                 10.0         18.2044        32.3251
-69.2298  40.0251                 12.0         16.2950        32.3521
-70.3633  40.1794                 14.0         15.8942        32.2599
-71.1449  40.1194                 19.0         12.8222        32.6560
-71.8850  40.2324                 20.0         12.7276        32.1592
-72.9134  40.5764                 21.0         18.2056        32.3251
-73.7517  40.0532                 21.0         14.1696        32.4267
-72.8647  39.4307                 22.0         19.7889        34.8207
-72.5357  39.2962                 25.0         14.2500        32.2904
-73.3573  39.3337                 31.0         15.8506        34.8324
-73.9067  39.5502                 32.0         12.6375        32.2130
-74.4051  39.1722                 35.0         15.2509        32.3775
-74.0736  38.7792                 36.0         18.2094        32.3248
-73.4073  38.4777                 40.0         12.6939        32.2904
-74.4132  38.4976                 40.0         13.5422        32.4733
-74.8676  38.0192                 41.0         13.1578        32.4603
-74.3009  37.7251                 50.0         15.1565        32.3805
-75.0514  37.6279                 50.0         13.2847        32.5039
-75.2359  37.3665                 51.0         11.5826        32.3627
-75.6720  37.0883                 52.0         12.2168        34.5628
-74.9524  36.9109                 53.0         10.2736        32.8280
-75.0004  36.5290                 61.0         12.7248        32.6154

                    Sigma-t  Sigma-Theta  Oxygen(mg/L)  \
longitude latitude
-71.4220  41.3639   22.6140      22.6141       7.48715
-71.0219  41.1282   24.1367      24.1368       8.67045
-70.7567  40.9404   23.0926      23.0928       8.03996
-70.3816  40.8762   23.4993      23.4995       8.24726
-69.9003  40.4664   23.1751      23.1752       7.95340
-69.1302  40.8105   23.3730      23.3731       8.14901
-68.3372  40.6436   22.9117      22.9121       7.85928
-68.3369  41.4818   24.1483      24.1485       8.64942
-67.8178  41.4534   23.1748      23.1753       7.93584
-69.2298  40.0251   23.6452      23.6456       8.30100
-70.3633  40.1794   23.6646      23.6650       8.62438
-71.1449  40.1194   24.6123      24.6128       9.48941
-71.8850  40.2324   24.2459      24.2464       8.43779
-72.9134  40.5764   23.1746      23.1754       7.91882
-73.7517  40.0532   24.1642      24.1648       7.97431
-72.8647  39.4307   24.6804      24.6814       7.85690
-72.5357  39.2962   24.0423      24.0430       8.27137
-73.3573  39.3337   25.6527      25.6538       7.76798
-73.9067  39.5502   24.3049      24.3057       8.32659
-74.4051  39.1722   23.8967      23.8978       7.77990
-74.0736  38.7792   23.1734      23.1749       7.92575
-73.4073  38.4777   24.3540      24.3550       8.24747
-74.4132  38.4976   24.3283      24.3294       7.79910
-74.8676  38.0192   24.3950      24.3961       7.88025
-74.3009  37.7251   23.9195      23.9211       7.77602
-75.0514  37.6279   24.4035      24.4049       7.77955
-75.2359  37.3665   24.6182      24.6194       8.25351
-75.6720  37.0883   26.2079      26.2093       6.97844
-74.9524  36.9109   25.2103      25.2113       7.42241
-75.0004  36.5290   24.5998      24.6014       7.70288

                    Chlorophyll Fluorescence(Âµg/L)  NO3+NO2(ÂµM)  Si(OH)4 (ÂµM)  \
longitude latitude
-71.4220  41.3639                         0.609925         0.09          1.01
-71.0219  41.1282                         3.278280         0.59          2.32
-70.7567  40.9404                         1.686100         0.09          1.66
-70.3816  40.8762                         1.324870         0.04          1.16
-69.9003  40.4664                         3.973100         0.09          0.29
-69.1302  40.8105                         1.482800         0.09          1.53
-68.3372  40.6436                         1.424060         0.09          1.12
-68.3369  41.4818                         2.900740         0.70          2.35
-67.8178  41.4534                         3.883680         0.05          0.29
-69.2298  40.0251                         2.846980         0.05          1.66
-70.3633  40.1794                         3.634420         0.09          1.99
-71.1449  40.1194                         2.958710         0.41          1.35
-71.8850  40.2324                         2.376790         1.28          2.48
-72.9134  40.5764                         4.093690         0.04          0.43
-73.7517  40.0532                         1.670840         1.62          2.57
-72.8647  39.4307                         0.975593         0.10          1.06
-72.5357  39.2962                         3.721510         0.19          2.48
-73.3573  39.3337                         2.297100         2.29          2.50
-73.9067  39.5502                         1.806580         1.31          2.64
-74.4051  39.1722                         1.785270         0.71          2.59
-74.0736  38.7792                         3.978310         0.09          0.19
-73.4073  38.4777                         1.445230         1.66          2.60
-74.4132  38.4976                         1.014950         2.71          3.14
-74.8676  38.0192                         1.594900         0.86          6.53
-74.3009  37.7251                         1.820390         1.04          2.70
-75.0514  37.6279                         0.955544         2.83          3.40
-75.2359  37.3665                         1.211180         2.07          3.19
-75.6720  37.0883                         0.661353         7.38          4.47
-74.9524  36.9109                         0.652899         5.48          8.17
-75.0004  36.5290                         0.791004         2.97          3.48

                    PO4 (ÂµM)
longitude latitude
-71.4220  41.3639       0.31
-71.0219  41.1282       0.38
-70.7567  40.9404       0.23
-70.3816  40.8762       0.39
-69.9003  40.4664       0.36
-69.1302  40.8105       0.25
-68.3372  40.6436       0.32
-68.3369  41.4818       0.54
-67.8178  41.4534       0.39
-69.2298  40.0251       0.50
-70.3633  40.1794       0.24
-71.1449  40.1194       0.43
-71.8850  40.2324       0.42
-72.9134  40.5764       0.43
-73.7517  40.0532       0.45
-72.8647  39.4307       0.17
-72.5357  39.2962       0.37
-73.3573  39.3337       0.50
-73.9067  39.5502       0.49
-74.4051  39.1722       0.46
-74.0736  38.7792       0.38
-73.4073  38.4777       0.52
-74.4132  38.4976       0.53
-74.8676  38.0192       0.67
-74.3009  37.7251       0.40
-75.0514  37.6279       0.59
-75.2359  37.3665       0.55
-75.6720  37.0883       0.66
-74.9524  36.9109       0.66
-75.0004  36.5290       0.54

In [47]:
df1[df2.columns.values][df1.index == df2.index] = df2

ValueError: Lengths must match to compare

In [46]:
df1 = df1.assign(df2.columns.values)

TypeError: assign() takes 1 positional argument but 2 were given

In [45]:
for column in df2.columns.values:
    df1.assign(column)

TypeError: assign() takes 1 positional argument but 2 were given

In [41]:
for column in df2.columns.values:
    df1[column] = np.nan

In [51]:
df3 = df1.merge (df2)

ValueError: 'latitude' is both an index level and a column label, which is ambiguous.

In [4]:
df3 = df1.merge (df2, on = ["latitude","longitude"])

In [5]:
df3

,latitude,longitude,date_x,depth_x,temperature,salinity,chl_ctd,pc_ctd,cdom_ctd,chl_a676,...,Sample Press(dBar),Temperature(C),Salinity(psu),Sigma-t,Sigma-Theta,Oxygen(mg/L),Chlorophyll Fluorescence(Âµg/L),NO3+NO2(ÂµM),Si(OH)4 (ÂµM),PO4 (ÂµM)
0,41.3639,-71.4220,2018-08-22 20:05:33.0,4,22.9616,31.3731,3.0008,0.1708,2.2575,6.0672,...,2.0,20.5540,32.3729,22.6140,22.6141,7.48715,0.609925,0.09,1.01,0.31
1,41.1282,-71.0219,2018-08-23 06:55:34.0,4,20.2587,31.8626,0.9196,0.1067,8.2173,2.2207,...,2.0,13.0719,32.1046,24.1367,24.1368,8.67045,3.278280,0.59,2.32,0.38
2,40.9404,-70.7567,2018-08-23 11:15:34.0,4,20.6970,32.2132,0.5082,0.0854,1.4900,2.0012,...,3.0,18.3394,32.2607,23.0926,23.0928,8.03996,1.686100,0.09,1.66,0.23
3,40.8762,-70.3816,2018-08-23 16:25:34.0,4,19.0128,32.3183,0.6292,0.0427,1.3545,2.4230,...,3.0,16.8980,32.3425,23.4993,23.4995,8.24726,1.324870,0.04,1.16,0.39
4,40.4664,-69.9003,2018-08-23 23:48:27.0,4,21.9741,32.6036,NaN,0.0427,6.8628,1.8721,...,3.0,18.2030,32.3250,23.1751,23.1752,7.95340,3.973100,0.09,0.29,0.36
5,40.8105,-69.1302,2018-08-24 05:28:27.0,4,18.2505,32.4054,0.6897,0.5124,2.2575,2.3337,...,3.0,17.2037,32.2708,23.3730,23.3731,8.14901,1.482800,0.09,1.53,0.25
6,40.6436,-68.3372,2018-08-24 11:38:26.0,4,19.3320,32.1945,0.3509,0.0427,1.6254,1.7692,...,10.0,19.5463,32.4196,22.9117,22.9121,7.85928,1.424060,0.09,1.12,0.32
7,41.4818,-68.3369,2018-08-24 17:28:27.0,4,18.0526,32.2973,0.4961,0.0427,1.8512,2.4932,...,10.0,13.0493,32.1139,24.1483,24.1485,8.64942,2.900740,0.70,2.35,0.54
8,41.4534,-67.8178,2018-08-25 00:07:32.0,4,18.7867,32.3103,2.4926,0.0214,1.8963,6.0561,...,10.0,18.2044,32.3251,23.1748,23.1753,7.93584,3.883680,0.05,0.29,0.39
9,40.7645,-67.5984,2018-08-25 07:27:31.0,4,23.7608,34.1365,NaN,0.0427,1.1287,1.9578,...,10.0,NaN,NaN,NaN,NaN,NaN,2.719740,0.10,1.83,0.37
10,40.0251,-69.2298,2018-08-25 22:10:50.0,4,23.1031,33.4401,0.1452,0.0640,1.1739,1.7505,...,12.0,16.2950,32.3521,23.6452,23.6456,8.30100,2.846980,0.05,1.66,0.50
11,40.1794,-70.3633,2018-08-26 06:10:51.0,4,22.6330,32.8449,0.1573,0.0427,1.0836,1.8539,...,14.0,15.8942,32.2599,23.6646,23.6650,8.62438,3.634420,0.09,1.99,0.24
12,40.1194,-71.1449,2018-08-26 14:20:51.0,4,22.9175,32.9570,0.1573,0.0427,1.2642,1.8770,...,19.0,12.8222,32.6560,24.6123,24.6128,9.48941,2.958710,0.41,1.35,0.43
13,40.2324,-71.8850,2018-08-26 21:10:51.0,4,24.1394,32.4753,0.1936,0.0854,1.0836,1.9027,...,20.0,12.7276,32.1592,24.2459,24.2464,8.43779,2.376790,1.28,2.48,0.42
14,40.5764,-72.9134,2018-08-27 04:10:23.0,4,22.6636,31.3408,0.5203,0.0427,2.2575,2.0954,...,21.0,18.2056,32.3251,23.1746,23.1754,7.91882,4.093690,0.04,0.43,0.43
15,40.0532,-73.7517,2018-08-27 11:20:23.0,4,23.6954,30.6937,0.5082,0.0854,2.6187,2.3289,...,21.0,14.1696,32.4267,24.1642,24.1648,7.97431,1.670840,1.62,2.57,0.45
16,39.4307,-72.8647,2018-08-27 17:50:24.0,4,25.3235,31.9266,0.1210,0.1281,1.2190,1.7989,...,22.0,19.7889,34.8207,24.6804,24.6814,7.85690,0.975593,0.10,1.06,0.17
17,39.2962,-72.5357,2018-08-27 22:56:31.0,4,25.2939,33.0843,0.1331,0.0854,1.1739,1.7855,...,25.0,14.2500,32.2904,24.0423,24.0430,8.27137,3.721510,0.19,2.48,0.37
18,39.3337,-73.3573,2018-08-28 06:46:30.0,4,24.7022,31.2891,0.2299,0.0854,1.9866,NaN,...,31.0,15.8506,34.8324,25.6527,25.6538,7.76798,2.297100,2.29,2.50,0.50
19,39.5502,-73.9067,2018-08-28 12:36:31.0,4,24.8160,30.3669,0.5082,0.0640,3.1605,2.5570,...,32.0,12.6375,32.2130,24.3049,24.3057,8.32659,1.806580,1.31,2.64,0.49
20,39.1722,-74.4051,2018-08-28 17:36:30.0,4,25.7304,30.7732,0.4961,0.0427,2.2575,2.4827,...,35.0,15.2509,32.3775,23.8967,23.8978,7.77990,1.785270,0.71,2.59,0.46
21,38.7792,-74.0736,2018-08-29 00:09:50.0,4,26.0023,31.1452,0.2783,0.1067,1.7157,2.1408,...,36.0,18.2094,32.3248,23.1734,23.1749,7.92575,3.978310,0.09,0.19,0.38
22,38.4777,-73.4073,2018-08-29 06:19:49.0,4,26.5776,31.8468,0.1089,0.0854,1.4448,1.7832,...,40.0,12.6939,32.2904,24.3540,24.3550,8.24747,1.445230,1.66,2.60,0.52
23,38.4976,-74.4132,2018-08-29 11:54:00.0,4,25.7600,31.2110,NaN,NaN,NaN,NaN,...,40.0,13.5422,32.4733,24.3283,24.3294,7.79910,1.014950,2.71,3.14,0.53
24,38.0192,-74.8676,2018-08-29 17:29:50.0,4,26.2000,30.0910,0.1331,0.0854,2.7090,1.7313,...,41.0,13.1578,32.4603,24.3950,24.3961,7.88025,1.594900,0.86,6.53,0.67
25,37.7251,-74.3009,2018-08-29 23:19:41.0,4,27.0474,32.2162,0.1089,0.0854,1.4448,1.7768,...,50.0,15.1565,32.3805,23.9195,23.9211,7.77602,1.820390,1.04,2.70,0.40
26,37.6279,-75.0514,2018-08-30 04:39:41.0,4,26.5379,31.4190,0.1089,0.0427,1.4448,1.7917,...,50.0,13.2847,32.5039,24.4035,24.4049,7.77955,0.955544,2.83,3.40,0.59
27,37.3665,-75.2359,2018-08-30 09:49:42.0,4,26.3338,31.5520,0.1089,0.0427,1.4900,1.8736,...,51.0,11.5826,32.3627,24.6182,24.6194,8.25351,1.211180,2.07,3.19,0.55
28,37.0883,-75.6720,2018-08-30 14:26:03.0,4,25.1800,31.1590,NaN,NaN,NaN,NaN,...,52.0,12.2168,34.5628,26.2079,26.2093,6.97844,0.661353,7.38,4.47,0.66
29,36.9109,-74.9524,2018-08-30 19:19:42.0,4,27.1761,30.9254,0.1210,0.0854,1.3997,1.8524,...,53.0,10.2736,32.8280,25.2103,25.2113,7.42241,0.652899,5.48,8.17,0.66
30,36.5290,-75.0004,2018-08-30 23:49:42.0,4,27.6020,30.3250,0.1331,0.0427,1.4448,1.8052,...,61.0,12.7248,32.6154,24.5998,24.6014,7.70288,0.791004,2.97,3.48,0.54

In [6]:
df1

,latitude,longitude,date,depth,temperature,salinity,chl_ctd,pc_ctd,cdom_ctd,chl_a676,Unnamed: 10
0,41.3639,-71.4220,2018-08-22 20:05:33.0,4,22.9616,31.3731,3.0008,0.1708,2.2575,6.0672,NaN
1,41.3397,-71.4215,2018-08-22 20:15:34.0,4,22.9605,31.3645,1.4036,0.0000,3.7926,4.5728,NaN
2,41.3143,-71.4218,2018-08-22 20:25:34.0,4,22.8414,31.5827,1.0527,0.0854,9.7975,3.6196,NaN
3,41.2886,-71.4227,2018-08-22 20:35:34.0,4,22.6832,31.8200,0.6050,0.0640,2.5284,2.4087,NaN
4,41.2631,-71.4226,2018-08-22 20:45:34.0,4,22.2266,32.0359,0.6655,0.1067,12.1454,2.2538,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1153,36.6353,-75.0009,2018-08-30 23:09:42.0,4,27.3766,31.0626,0.1210,0.0854,1.1739,1.7724,NaN
1154,36.6121,-75.0006,2018-08-30 23:19:42.0,4,27.3393,31.0169,0.1089,0.0427,1.4448,1.7669,NaN
1155,36.5841,-75.0000,2018-08-30 23:29:42.0,4,27.5079,30.4349,0.1452,0.0427,1.5351,1.8033,NaN
1156,36.5565,-75.0001,2018-08-30 23:39:42.0,4,27.5168,30.4410,0.1452,0.0640,1.4448,1.7968,NaN
1157,36.5290,-75.0004,2018-08-30 23:49:42.0,4,27.6020,30.3250,0.1331,0.0427,1.4448,1.8052,NaN

In [7]:
df2

,latitude,longitude,date,depth,Bottom Depth(m),Sample Press(dBar),Temperature(C),Salinity(psu),Sigma-t,Sigma-Theta,Oxygen(mg/L),Chlorophyll Fluorescence(Âµg/L),NO3+NO2(ÂµM),Si(OH)4 (ÂµM),PO4 (ÂµM)
0,41.3639,-71.4220,05:33.0,4.0,61.0,2.0,20.5540,32.3729,22.6140,22.6141,7.48715,0.609925,0.09,1.01,0.31
1,41.1282,-71.0219,55:34.0,4.0,67.0,2.0,13.0719,32.1046,24.1367,24.1368,8.67045,3.278280,0.59,2.32,0.38
2,40.9404,-70.7567,15:34.0,4.0,44.0,3.0,18.3394,32.2607,23.0926,23.0928,8.03996,1.686100,0.09,1.66,0.23
3,40.8762,-70.3816,25:34.0,4.0,53.0,3.0,16.8980,32.3425,23.4993,23.4995,8.24726,1.324870,0.04,1.16,0.39
4,40.4664,-69.9003,48:27.0,4.0,39.0,3.0,18.2030,32.3250,23.1751,23.1752,7.95340,3.973100,0.09,0.29,0.36
5,40.8105,-69.1302,28:27.0,4.0,64.0,3.0,17.2037,32.2708,23.3730,23.3731,8.14901,1.482800,0.09,1.53,0.25
6,40.6436,-68.3372,38:26.0,4.0,61.0,10.0,19.5463,32.4196,22.9117,22.9121,7.85928,1.424060,0.09,1.12,0.32
7,41.4818,-68.3369,28:27.0,4.0,67.0,10.0,13.0493,32.1139,24.1483,24.1485,8.64942,2.900740,0.70,2.35,0.54
8,41.4534,-67.8178,07:32.0,4.0,39.0,10.0,18.2044,32.3251,23.1748,23.1753,7.93584,3.883680,0.05,0.29,0.39
9,40.7645,-67.5984,27:31.0,4.0,64.0,10.0,NaN,NaN,NaN,NaN,NaN,2.719740,0.10,1.83,0.37
10,40.0251,-69.2298,10:50.0,4.0,53.0,12.0,16.2950,32.3521,23.6452,23.6456,8.30100,2.846980,0.05,1.66,0.50
11,40.1794,-70.3633,10:51.0,4.0,44.0,14.0,15.8942,32.2599,23.6646,23.6650,8.62438,3.634420,0.09,1.99,0.24
12,40.1194,-71.1449,20:51.0,4.0,61.0,19.0,12.8222,32.6560,24.6123,24.6128,9.48941,2.958710,0.41,1.35,0.43
13,40.2324,-71.8850,10:51.0,4.0,67.0,20.0,12.7276,32.1592,24.2459,24.2464,8.43779,2.376790,1.28,2.48,0.42
14,40.5764,-72.9134,10:23.0,4.0,39.0,21.0,18.2056,32.3251,23.1746,23.1754,7.91882,4.093690,0.04,0.43,0.43
15,40.0532,-73.7517,20:23.0,4.0,64.0,21.0,14.1696,32.4267,24.1642,24.1648,7.97431,1.670840,1.62,2.57,0.45
16,39.4307,-72.8647,50:24.0,4.0,248.0,22.0,19.7889,34.8207,24.6804,24.6814,7.85690,0.975593,0.10,1.06,0.17
17,39.2962,-72.5357,56:31.0,4.0,44.0,25.0,14.2500,32.2904,24.0423,24.0430,8.27137,3.721510,0.19,2.48,0.37
18,39.3337,-73.3573,46:30.0,4.0,248.0,31.0,15.8506,34.8324,25.6527,25.6538,7.76798,2.297100,2.29,2.50,0.50
19,39.5502,-73.9067,36:31.0,4.0,67.0,32.0,12.6375,32.2130,24.3049,24.3057,8.32659,1.806580,1.31,2.64,0.49
20,39.1722,-74.4051,36:30.0,4.0,53.0,35.0,15.2509,32.3775,23.8967,23.8978,7.77990,1.785270,0.71,2.59,0.46
21,38.7792,-74.0736,09:50.0,4.0,39.0,36.0,18.2094,32.3248,23.1734,23.1749,7.92575,3.978310,0.09,0.19,0.38
22,38.4777,-73.4073,19:49.0,4.0,67.0,40.0,12.6939,32.2904,24.3540,24.3550,8.24747,1.445230,1.66,2.60,0.52
23,38.4976,-74.4132,54:00.0,4.0,64.0,40.0,13.5422,32.4733,24.3283,24.3294,7.79910,1.014950,2.71,3.14,0.53
24,38.0192,-74.8676,29:50.0,4.0,44.0,41.0,13.1578,32.4603,24.3950,24.3961,7.88025,1.594900,0.86,6.53,0.67
25,37.7251,-74.3009,19:41.0,4.0,53.0,50.0,15.1565,32.3805,23.9195,23.9211,7.77602,1.820390,1.04,2.70,0.40
26,37.6279,-75.0514,39:41.0,4.0,64.0,50.0,13.2847,32.5039,24.4035,24.4049,7.77955,0.955544,2.83,3.40,0.59
27,37.3665,-75.2359,49:42.0,4.0,67.0,51.0,11.5826,32.3627,24.6182,24.6194,8.25351,1.211180,2.07,3.19,0.55
28,37.0883,-75.6720,26:03.0,4.0,248.0,52.0,12.2168,34.5628,26.2079,26.2093,6.97844,0.661353,7.38,4.47,0.66
29,36.9109,-74.9524,19:42.0,4.0,61.0,53.0,10.2736,32.8280,25.2103,25.2113,7.42241,0.652899,5.48,8.17,0.66
30,36.5290,-75.0004,49:42.0,4.0,64.0,61.0,12.7248,32.6154,24.5998,24.6014,7.70288,0.791004,2.97,3.48,0.54
31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
#the line below effectively threw in the df2 data to df1 using lat/long as guides

In [ ]:
#the reason t

In [8]:
df3 = df1.merge (df2, on = ["latitude","longitude"], how = "left")

In [9]:
df3

,latitude,longitude,date_x,depth_x,temperature,salinity,chl_ctd,pc_ctd,cdom_ctd,chl_a676,...,Sample Press(dBar),Temperature(C),Salinity(psu),Sigma-t,Sigma-Theta,Oxygen(mg/L),Chlorophyll Fluorescence(Âµg/L),NO3+NO2(ÂµM),Si(OH)4 (ÂµM),PO4 (ÂµM)
0,41.3639,-71.4220,2018-08-22 20:05:33.0,4,22.9616,31.3731,3.0008,0.1708,2.2575,6.0672,...,2.0,20.5540,32.3729,22.6140,22.6141,7.48715,0.609925,0.09,1.01,0.31
1,41.3397,-71.4215,2018-08-22 20:15:34.0,4,22.9605,31.3645,1.4036,0.0000,3.7926,4.5728,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,41.3143,-71.4218,2018-08-22 20:25:34.0,4,22.8414,31.5827,1.0527,0.0854,9.7975,3.6196,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,41.2886,-71.4227,2018-08-22 20:35:34.0,4,22.6832,31.8200,0.6050,0.0640,2.5284,2.4087,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,41.2631,-71.4226,2018-08-22 20:45:34.0,4,22.2266,32.0359,0.6655,0.1067,12.1454,2.2538,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1153,36.6353,-75.0009,2018-08-30 23:09:42.0,4,27.3766,31.0626,0.1210,0.0854,1.1739,1.7724,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1154,36.6121,-75.0006,2018-08-30 23:19:42.0,4,27.3393,31.0169,0.1089,0.0427,1.4448,1.7669,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1155,36.5841,-75.0000,2018-08-30 23:29:42.0,4,27.5079,30.4349,0.1452,0.0427,1.5351,1.8033,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1156,36.5565,-75.0001,2018-08-30 23:39:42.0,4,27.5168,30.4410,0.1452,0.0640,1.4448,1.7968,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1157,36.5290,-75.0004,2018-08-30 23:49:42.0,4,27.6020,30.3250,0.1331,0.0427,1.4448,1.8052,...,61.0,12.7248,32.6154,24.5998,24.6014,7.70288,0.791004,2.97,3.48,0.54